#!/bin/sh

#remove the old cscope file listing
rm -f cscope.files
touch cscope.files

#expand the the CSCOPE_SOURCES environment variable.
sources=`echo $CSCOPE_SOURCES | sed 's/:/ /g'`

for n in $sources; do
    echo "Finding sources in $n."
    find $n -name "*.c" -or -name "*.h" -or -name "*.cpp" -or -name "*.java" >> cscope.files
done

echo "Finding sources in `pwd`."
find . -name "*.c" -or -name "*.h" -or -name "*.cpp" -or -name "*.java" >> cscope.files

echo "Building cscope database."
cscope -b -q -i cscope.files > /dev/null 2>&1

echo "Building ctags database."
rm -f tags
cat cscope.files | xargs ctags -a -f tags > /dev/null 2>&1

echo "done."
