#!/bin/sh -x

find . -name "*.c" -or -name "*.h" -or -name "*.cpp" -or -name "*.java" > cscope.files
cscope -b -q -i cscope.files > /dev/null 2>&1
rm -f tags
cat cscope.files | xargs ctags -a -f tags > /dev/null 2>&1
